import { server_host } from "./constant";

export const url_upload = server_host + 'upload';
export const url_save_article = server_host + 'saveArticle';
export const url_save_msg = server_host + 'saveMsg';
export const url_save_role = server_host + 'addRole';
export const url_save_article_msg = server_host + 'addOneArticleMsg';
export const url_get_msg = server_host + 'getMsg';
export const url_get_article_msg = server_host + 'getArticleMsg';
export const url_get_article = server_host + 'getArticle';
export const url_get_user = server_host + 'getUser';
export const url_get_role = server_host + 'getRole';
export const url_get_image = server_host + 'getImages';
export const url_login_back = server_host + 'loginBack';
export const url_user_rigster = server_host + 'userRigster';
export const url_delete_article = server_host + 'deleteArticle';
export const url_delete_image = server_host + 'deleteImage';
export const url_delete_user = server_host + 'deleteUser';
export const url_delete_role = server_host + 'deleteRole';
export const url_update_role = server_host + 'updateRole';